# Generated by Django 3.1.7 on 2021-03-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('configuration', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=5)),
                ('paid_by', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='device.users')),
            ],
        ),
    ]
    atomic = False
