# Generated by Django 3.1.7 on 2021-03-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210316_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
    atomic = False