# Generated by Django 3.1.7 on 2021-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20210321_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='departament',
            field=models.CharField(default='name of dep.', max_length=20),
        ),
    ]
